version: 1.0.{build}
image: Ubuntu2204

platform:
  - ARM

install:
  - git clone --depth=1 --branch=4.x https://github.com/opencv/opencv.git
  - git clone --depth=1 --branch=edcolor https://github.com/sturkmen72/opencv_contrib.git
  - git clone --depth=1 --branch=animated_webp_support https://github.com/sturkmen72/opencv_extra.git
  - export OPENCV_TEST_DATA_PATH=$(pwd)/opencv_extra/testdata
  - export OPENCV_DIR=$(pwd)/build-opencv
  - mkdir build-opencv
  - cd build-opencv
  - cmake -DBUILD_opencv_java=OFF -DWITH_JASPER=OFF -DWITH_WEBP=OFF -DBUILD_IPP_IW=OFF -DBUILD_ITT=OFF -DWITH_OPENEXR=OFF -DWITH_OPENJPEG=OFF -DBUILD_PROTOBUF=OFF -DWITH_TIFF=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_java=OFF -DBUILD_line_descriptor=OFF -DBUILD_signal=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_gapi=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_aruco=OFF -DBUILD_opencv_bioinspired=OFF -DBUILD_opencv_fuzzy=OFF -DBUILD_opencv_hfs=OFF -DBUILD_opencv_img_hash=OFF -DBUILD_opencv_surface_matching=OFF -DBUILD_opencv_bgsegm=OFF -DBUILD_opencv_intensity_transform=OFF -DBUILD_opencv_optflow=OFF -DBUILD_opencv_phase_unwrapping=OFF -DBUILD_opencv_plot=OFF -DBUILD_opencv_rapid=OFF -DBUILD_opencv_reg=OFF -DBUILD_opencv_rgbd=OFF -DBUILD_opencv_saliency=OFF -DBUILD_opencv_shape=OFF -DBUILD_opencv_stereo=OFF -DBUILD_opencv_structured_light=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_tracking=OFF -DBUILD_opencv_videostab=OFF -DBUILD_opencv_xfeatures2d=OFF -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib/modules ../opencv
  - make
  - cd ..
  - cd build-opencv/bin/
  - ./opencv_test_ximgproc
  - cd ..
  - cd ..

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - make

test_script:
  - ./test_it /projects/ed-lib/planet_glow.jpg
  - ./test_ED /projects/ed-lib/billiard.jpg
  - ./video_test /projects/ed-lib/opencv/samples/data/vtest.avi --scale=2 --counter=100
  - ./video_test /projects/ed-lib/opencv/samples/data/vtest.avi --scale=4 --counter=50
  - ./video_test /projects/ed-lib/opencv/samples/data/vtest.avi --scale=8 --counter=50
  - ./video_test /projects/ed-lib/opencv/samples/data/vtest.avi --scale=16 --counter=5
  - ./video_test /projects/ed-lib/opencv/samples/data/vtest.avi --scale=23 --counter=1
  - ./video_test http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

artifacts:
  - path: .\build\CIRCLES_AND_ELLIPSES_RESULT_IMAGE.jpg
    name: CIRCLES_AND_ELLIPSES_RESULT_IMAGE.jpg
  - path: .\build\GradImage.png
    name: GradImage.png
  - path: .\build\AnchorImage.png
    name: AnchorImage.png
  - path: .\build\EdgeImage.png
    name: Edge Image
  - path: .\build\EdgeImage-Color.png
    name: Edge Image (color)
  - path: .\build\LinesImage.png
    name: Lines Image
  - path: .\build\LinesImage-Color.png
    name: Lines Image (color)
  - path: .\build\EdgeImage-PF.png
    name: Edge Image (PF)
  - path: .\build\EllipsImage-Original.png
    name: Ellipses Image ( Original )
  - path: .\build\EllipsImage-OpenCV.png
    name: Ellipses Image ( OpenCV )
  - path: .\build\EllipsImageColor-Original.png
    name: Ellipses Image ( color Original )
  - path: .\build\EllipsImageColor-OpenCV.png
    name: Ellipses Image ( color OpenCV )
